import { Center, Box, HStack } from "@chakra-ui/react";
import WeatherHourBlockTemp from "./WeatherHourBlockTemp";

interface Prop {
  day: number;
  data: any;
}

function WeatherDetailTemp({ day, data }: Prop) {
  return (
    <Box>
      <Center display="block" mr="auto" ml="auto" mt="2rem">
        <HStack textAlign="center">
          <WeatherHourBlockTemp
            day={day}
            normalHour="12:00"
            militaryHour={0}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="1:00"
            militaryHour={1}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="2:00"
            militaryHour={2}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="3:00"
            militaryHour={3}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="4:00"
            militaryHour={4}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="5:00"
            militaryHour={5}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="6:00"
            militaryHour={6}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="7:00"
            militaryHour={7}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="8:00"
            militaryHour={8}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="9:00"
            militaryHour={9}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="10:00"
            militaryHour={10}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="11:00"
            militaryHour={11}
            data={data}
          />
        </HStack>
        <HStack textAlign="center" mt="2rem">
          <WeatherHourBlockTemp
            day={day}
            normalHour="12:00"
            militaryHour={12}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="1:00"
            militaryHour={13}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="2:00"
            militaryHour={14}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="3:00"
            militaryHour={15}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="4:00"
            militaryHour={16}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="5:00"
            militaryHour={17}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="6:00"
            militaryHour={18}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="7:00"
            militaryHour={19}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="8:00"
            militaryHour={20}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="9:00"
            militaryHour={21}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="10:00"
            militaryHour={22}
            data={data}
          />
          <WeatherHourBlockTemp
            day={day}
            normalHour="11:00"
            militaryHour={23}
            data={data}
          />
        </HStack>
      </Center>
    </Box>
  );
}

export default WeatherDetailTemp;
